[package]
name = "kfhe"
version = "0.1.0"
authors = ["hamadatakaki <i16hamadat@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
rand_distr = "0.4.1"
